doc/TestFile.txt
I edited TestFile incrementing the version and adding my name
=> Updated TestFile.txt

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Based on GitHub default issue templates
=> Add issue templates for Kanban board

.github/ISSUE_TEMPLATE/bug_report.md
For some reason this change did not save that last time I updated
=> Add automatic label to bug template

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/Book.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/ChatRoom.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/Location.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/ImageMessage.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/LocationMessage.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/Message.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/TextMessage.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/BorrowedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/OwnedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/User.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/UserProfile.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/OwnedBookTests.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/UserTests.java
Move variable instantiation into class constructors.
Change instances of `HashMap` in variable declaration to `Map` to allow for Polymorphism.
Group `User`, `OwnedBook`, `BorrowedBook`, and `UserProfile` into their own package, resembling the database structure.
Fix whitespace (again).
=> Refactor model classes

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookController.java
Just added the basic controller, let me know if this is missing anything. I'll put everything else into a separate PR
=> adding BookController

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/Message.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/MessageTests.java
Let me know if there is anything I need to include/missed
=> added MessageTests and corresponding exceptions in Message class

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/ChatController.java
let me know if there is anything to add, or if I missed functionality
=> added skeleton for chat controller

app/src/main/res/layout/activity_main.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
PR sooner than later so it won't mess people up
Duplicated my commit when I merged master
=> Color rename for clarity

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/ImageMessage.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/Message.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/ImageMessageTests.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/TextMessageTests.java
let me know if there is anything to add
=> Feature image message test

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/message/LocationMessage.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/LocationMessageTests.java
let me know if there is anything to add
=> added LocationMessageTests and functionality to LocationMessage

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/BorrowedBook.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/BorrowedBookTests.java
let me know if anything more is needed
=> added BorrowedBookTests and modified the object

app/build.gradle, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/viewmybook/AddNewBookActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/viewmybook/EditBookActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/ImageController.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/ImageControllerTests.java
Reworked and added method signatures and interfaces to work with Firebase's asynchronous functionality.
Implements ImageController methods.
Updates Espresso.
Adds unit tests for the ImageController (tests can't be ran without Firebase initialized to some app context AFAIK, so these tests currently don't run).
=> Complete ImageController

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookController.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/Book.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/BorrowedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/OwnedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/User.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/UserBook.java
I just have left to make tests and finish the transaction-related methods.
Making this PR to have the "public interface" (visible/public methods) available to people working on activities.
=> Nearly Complete BookController

app/src/main/res/layout/fragment_exchange.xml, app/src/main/res/layout/fragment_library.xml, app/src/main/res/layout/fragment_messages.xml
xml button aligns with function in main
=> button fix

app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/UserTests.java
Fixes UserTests to use the updated User class methods
=> Fix UserTests

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MyProfileActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewUserProfileActivity.java
=> quick fix with opening ellipses menu

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/UserProfile.java
basic comments for userProfile model,
=> User profile comments

app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/BookControllerTests.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookController.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/Book.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/BorrowedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/OwnedBook.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/UserBook.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/BookTests.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/BorrowedBookTests.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/OwnedBookTests.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/UserTests.java, build.gradle
Write Javadoc comments for `Book`, `UserBook`, `OwnedBook`, and `BorrowedBook`.  
Refactor `UserBook`, `OwnedBook`, and `BorrowedBook` classes to reflect proper usage.  
Update JUnit tests for `OwnedBook`, `BorrowedBook`, and `User` (since `User` uses the aforementioned classes)  
Rename `getImage()` and `setImage()` in Book to `getImageId()` and `setImageId()` for Firebase's deserializer.
=> Add BookController tests, Refactor book model classes

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/AcceptedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/BorrowedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/ExchangeFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/RequestedFragment.java, app/src/main/res/layout/fragment_exchange_borrowed.xml, app/src/main/res/layout/fragment_exchange_requested.xml
The code from accepted window is added to the borrowed and the requested tabs
Also adds Javadoc to the classes
=> Populate Exchange Tab with temporary Lists

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewUserProfileActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/AcceptedFragment.java, app/src/main/res/layout/activity_view_profile.xml, app/src/main/res/layout/fragment_user_book.xml
allows transfer view book to view user of its owner
adds back button click on view book
- sets information on page from firebase 
- sets owner image in view book
=> View user + view book

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/BookList.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/ChatRoom.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/Location.java
as the name suggests javadoc comments
=> Javadoc on model classes

app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/BookParserTests.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/BookListProvider.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MainActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookParser.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/AcceptedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/BorrowedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/RequestedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/library/AllTabFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/library/AvailableFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/library/LoanedFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/BookRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/user/UserBook.java
Bug: It can take a few seconds for the books to show up in the lists
=> Add BookParser and Integrate it with Exchange/Library Fragments

app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/ImageController.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/SearchController.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/BookList.java, app/src/main/res/layout/fragment_search.xml
Search, behind the scenes, works as expected. Comments and javadoc stuff to follow. Results are currently not displaying
=> Fix search and merge conflicts

app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/MessageFragmentTests.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/MessagesFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/chatroom/ChatRoomItem.java, app/src/test/java/ca/ualberta/CMPUT3012019T02/alexandria/ChatRoomItemTests.java
unfortunately i was not able to get messageFragment tests done
=> Test for ChatRoomItem

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MyProfileActivity.java, app/src/main/res/menu/profile_settings.xml, app/src/main/res/values/strings.xml
adds sign out option and signs out current user, doesn't prompt if they really want it, to do later
=> added sign out button in my profile

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/adapter/BookRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java
search doesn't properly clear the results list before displaying, and their are other issues, but the basic implementation is working as intended
=> Search displays results

app/src/main/AndroidManifest.xml, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MainActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MyProfileActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewMyProfileActivity.java, app/src/main/res/layout/activity_my_profile.xml, app/src/main/res/layout/activity_view_my_profile.xml, app/src/main/res/menu/profile_settings.xml, app/src/main/res/values/strings.xml, doc/JavaDoc/ca/ualberta/CMPUT3012019T02/alexandria/activity/MyProfileActivity.html
UI updated to look cleaner, and now loads a lot smoother
Renamed it to ViewMyProfile
New lined lines that are longer than the 50? char soft limit
=> Cleans the UI and code for MyProfile

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java, app/src/main/res/layout/fragment_user_book.xml, app/src/main/res/menu/menu_user_book.xml, app/src/main/res/values/strings.xml
Looks a lot better with small screen and adds an ellipses menu.
=> Clean the UI in UserBookFragment

functions/search/index.js
Updated index to only include available books. Also fixed issue with free trail expiring with search. Also updated the script on the VM
=> Updated the index to only include available books

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/BookListItem.java
Search now focuses on EditText when the fragment loads.
Search updates the RecyclerView when new data is added to it. There is a slight delay due to the query.
=> Fixes to search

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/adapter/BookRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/adapter/OwnerRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/bookCatalogue/BookCatalogueFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/bookCatalogue/OwnerListFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/OwnerListItem.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/holder/OwnerViewHolder.java, app/src/main/res/layout/fragment_book_catalogue.xml, app/src/main/res/layout/fragment_book_catalogue_owners.xml, app/src/main/res/layout/item_owner.xml, app/src/main/res/layout/item_user.xml, app/src/main/res/values/strings.xml
=> Create Book Catalogue Page with appropriate Adapters

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/exchange/ExchangeFragment.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values/strings.xml
Scrolling is properly adjusted to the soft keyboard
Proper commit added to BookCatalogue PR, but testing when everything is merged is needed
=> Edit SearchFragment UI behavior

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/SearchFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/bookCatalogue/OwnerListFragment.java
Fixes crash null exception
Removes Keyboard when leaving Search Fragment
=> Hotfix Search Fragment

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MainActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/library/LibraryFragment.java, app/src/main/res/drawable/ic_add.xml, app/src/main/res/layout/fragment_library.xml, app/src/main/res/layout/fragment_library_all_tab.xml, app/src/main/res/layout/fragment_library_available.xml, app/src/main/res/layout/fragment_library_loaned.xml
Add padding to the bottom and changes add button
=> Correct Add Book UI

app/build.gradle, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ISBNLookup.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/myBook/MyBookTransactionFragment.java
Changes ISBNLookup activity to use ZXing scanner instead of ZBar.
Implements ISBN checking for exchanging and returning books.
=> Swap ZBar with ZXing barcode scanner

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/MainActivity.java
Obviously not the spinner we made. Needs a change from ProgressDialog to the actual spinner.
=> Add spinner to initial book list loading

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/adapter/OwnerRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/bookCatalogue/BookCatalogueFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/bookCatalogue/OwnerListFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/model/OwnerListItem.java
=> Implement auto-updating owner list (list of available book owners with the book available or requested)

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewMyProfileActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewUserProfileActivity.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/adapter/OwnerRecyclerViewAdapter.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java
Removes background resource if user has a profile picture.
Adds background resource if user has no profile picture.
=> User Profile Picture Transparency fix

app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/LoginActivityTests.java, app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewMyProfileActivityTests.java, app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/activity/ViewUserProfileActivityTests.java
All but one android Test now pass with this PR
=> Fix android tests and add view my profile tests

app/src/androidTest/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookControllerTests.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/cache/ObservableUserCache.java
Note: There is an issue where UserController createUser (and authenticate) can time out. So I've removed the time limit on those functions in the BookController Tests for now.
Warning: BookController Tests can take a long time to complete.
=> Fix Cache Update and Book Controller Tests

app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/controller/BookController.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/UserBookFragment.java, app/src/main/java/ca/ualberta/CMPUT3012019T02/alexandria/fragment/myBook/MyBookTransactionFragment.java
UserBookFragment now uses user perspective status instead of owner perspective.
MyBookTransactionFragment now displays user profiles correctly. 
- A user with no profile will now load properly
- A user with a profile picture with transparency will have their picture displayed properly
=> UserBookFragment status fix. Fix MyBookTransactionFragment user profile.
